// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hltjrtbulggtmaxotqvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsdGpydGJ1bGdndG1heG90cXZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Nzk4NjcsImV4cCI6MjA2NDM1NTg2N30.3wJ5wLtyh9f62vtx4MkbKV22vqTFHrVi1X4cjk9Q2YQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);